config/routes.rb
Rails.application.routes.draw do

  get 'error/index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/login'
  root :to => 'home#index'

  get 'home', to: 'home#index'
  get 'signup', to: 'users#new'
  get 'navbar', to: 'navbar#index'
  get 'study', to: 'study#home'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'

  get 'alphabet_answers/finished'
  get 'alphabet_answers/restart', to: 'alphabet_answers#restart'
  get 'alphabet_answers/begin', to: 'alphabet_answers#begin'
  
  get 'alphabet_answers/:alphabet_id', to: 'alphabet_answers#show'

  get 'page_not_found', to: 'error#show'

  resources :users
  resources :study
  resources :alphabets
  resources :alphabet_answers
end

app/models/alphabet.rb
class Alphabet < ApplicationRecord
end

app/models/alphabet_answer.rb
class AlphabetAnswer < ApplicationRecord
  belongs_to :alphabet
  belongs_to :user

  scope :correct_answers, -> { where(correct: true) }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, uniqueness: true, presence: true

  has_many :alphabet_answers

  def unanswered_questions
    alphabet_answers.where(answer: ["", nil])
  end
end

app/controllers/alphabet_answers_controller.rb
class AlphabetAnswersController < ApplicationController
  before_action :initialize_data, only: [:show]
  include AlphabetAnswersHelper

  def index
  end

  def show
  end

  def update
    @alphabet_answer = AlphabetAnswer.find(params[:id])

    @alphabet_answer.update(alphabet_answers_params)
    @alphabet_answer.correct = @alphabet_answer.alphabet.alphabet.upcase === @alphabet_answer.answer.upcase

    respond_to do |format|
      if @alphabet_answer.save
        if @alphabet_answer.correct
          if next_page(@alphabet_answer.alphabet.rank)
            format.html { redirect_to alphabet_answer_path(@alphabet_answer.alphabet.rank+1) }
            format.json { render :show, status: :created, location: alphabet_answer_path(@alphabet_answer.alphabet.rank+1) }
          else
            format.html { redirect_to alphabet_answers_finished_path }
            format.json { render :show, status: :created, location: alphabet_answers_finished_path }
          end
        else
          format.html { redirect_to alphabet_answer_path(@alphabet_answer.alphabet.rank), notice: 'Incorrect answer' }
        end
      end
    end
  end

  def restart
    current_user.alphabet_answers.destroy_all
    redirect_to alphabet_answers_path
  end

  def begin
    unless current_user.alphabet_answers.any?
      Alphabet.all.each do |alphabet|
        AlphabetAnswer.create(user_id: current_user.id, alphabet_id: alphabet.rank)
      end
    end

    redirect_to alphabet_answer_path(1)
  end

  def initialize_data
    @alphabet = Alphabet.find_by(rank: params[:alphabet_id])
    @alphabet_answer = AlphabetAnswer.find_by(user_id: current_user.id, alphabet_id: @alphabet.id) if @alphabet.present?
    send_404 unless @alphabet.present?
  end

  def alphabet_answers_params
    params.require(:alphabet_answer).permit(:answer, :alphabet_id)
  end

end

app/controllers/alphabets_controller.rb
class AlphabetsController < ApplicationController
  def index
    @alphabets = Alphabet.all
  end

  def alphabet_params
    params.require(:alphabets).permit(:answer)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    User.find_by(id: session[:user_id])
  end

  def send_404
    redirect_to page_not_found_path
  end

end

app/controllers/error_controller.rb
class ErrorController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
     @user = User.find_by(email: params[:email])
     if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to '/home'
     else
        redirect_to '/login'
     end
  end

  def login
  end
end

app/controllers/study/home_controller.rb
class HomeController < ApplicationController
  def index

  end

end

app/controllers/study_controller.rb
class StudyController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def login
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/alphabet_answers_helper.rb
module AlphabetAnswersHelper
  def next_page(rank)
    Alphabet.where(rank: rank+1)&.first&.rank
  end

  def previous_page(rank)
    Alphabet.where(rank: rank-1)&.first&.rank
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_helper.rb
module ErrorHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/study_helper.rb
module StudyHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/alphabet_answers/_form.html.erb
<div class="alphabet-form">
  <div class="direction row">
    <div class="col-md-6">
      <%= link_to 'Previous', alphabet_answer_path(previous_page(@alphabet.rank)), class: "float-left" if previous_page(@alphabet.rank) %>
    </div>
    <div class="col-md-6">
      <%= link_to 'Skip', alphabet_answer_path(next_page(@alphabet.rank)), class: "float-right" if next_page(@alphabet.rank) %>
    </div>
  </div>
  <center>
    <img src="<%= image_path(@alphabet.image_url) %>"><br/><br/>
    <div class="alert alert-primary" role="alert">
      <p><%= @alphabet.alphabet %></p>
    </div>
  </center>
  <% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
    <% end %>
  <%= form_for @alphabet_answer, method: 'patch' do |f| %>
    <div class="field">
      <%= f.label :answer %>
      <% if @alphabet_answer.correct %>
        <i class="fa fa-check" aria-hidden="true"></i>
      <% elsif @alphabet_answer.answer.present? %>
        <i class="fa fa-times" aria-hidden="true"></i>
      <% end %>
      <%= f.text_field :answer, class: "form-control" %>
      <br/>
      <%= f.hidden_field :alphabet_id, value: @alphabet.id %>
      <%= f.submit 'Submit', class: "btn btn-success" %>
    </div><!-- field -->
  <% end %>

  <input type="button" value="Reveal Answer" id="revealAnswer" class="btn btn-primary">
  <br/>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('#revealAnswer').click(function(){
      $('.alert').toggle();
    });
  })
</script>

app/views/alphabet_answers/finished.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Quiz Complete!</h1>
    <p>Your scores as highlighted:</p>
    <p><%= current_user.alphabet_answers.where(correct: true).count %>/<%= Alphabet.count %></p>
    <h2>Incorrect answers:</h2>

    <% current_user.alphabet_answers.where(correct: false).each do |incorrect| %>
      <p>Answered:<%= incorrect.answer %></p>
      <p>Actual answer:<%= incorrect.alphabet.alphabet %></p>
      <hr/>
    <% end %>

    <h2>Unanswered questions:</h2>
    <% unanswered_questions = current_user.unanswered_questions %>
    <% if unanswered_questions.any? %>
      <% unanswered_questions.each do |unanswered| %>
        <p><%= unanswered.alphabet.rank %>. <%= link_to unanswered.alphabet.alphabet, alphabet_answer_path(unanswered.alphabet.rank) %></p>
      <% end %>
    <% else %>
      <p>None!</p>
    <% end %>

    <%= link_to "Restart", alphabet_answers_restart_path, :data => {:confirm => 'This will remove all your current answers - Are you sure?'}, class: "btn btn-danger" %>
  </div>
</div>

app/views/alphabet_answers/index.html.erb
<br/><div class="jumbotron">
  <center>
    <%= link_to "Start Quiz", alphabet_answers_begin_path, class: "btn btn-primary" %>
  </center>
</div>

app/views/alphabet_answers/show.html.erb
<br/><div class="jumbotron">
  <%= render "form" %>
</div>

app/views/alphabets/index.html.erb
<div class="row">
  <% @alphabets.each do |alphabet| %>
  <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3 text-center">
    <div class="alphabet-wrapper">
      <img src="<%= image_path(alphabet.image_url)%>">
    </div>
    <p><%= alphabet.alphabet %></p>
  </div>
  <% end %>
</div>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Learn Tibetan</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", home_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About Us</a>
      </li>
    </ul>
  </div>
  <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
      <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <% if current_user %>
              <%= link_to "Start Learning", study_path %>
            <% else %>
              <%= link_to "Get Started", signup_path %>
            <% end %>
          </li>
      </ul>
  </div>
</nav>

app/views/home/index.html.erb
<div class="container">
  <h1>Get started today!</h1>
  <p>Sign up and start learning Tibetan alphabets for FREE!</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearnTibetan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if action_name == "index" %>
      <%= render "navbar" %>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/study/home.html.erb
<h1>Welcome.</h1>

<div class="row">
  <div class="col-sm-12">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Learn Tibetan Alphabets</h5>
        <p class="card-text">A fun way to learn the alphabets - just type what you see!</p>
        <%= link_to "Get Started", alphabet_answers_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email%>
    <%= form.text_field :email, class: "form-control"  %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control"  %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "form-control"  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="container">
  <h1>Sign Up</h1>

  <%= render 'form', user: @user %>

  <%= link_to 'Back', users_path %>
  
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>